### ISSUE TITLE
BudgetHistory violates clean architecture

### ISSUE THREAD

**Issue by by20c** [CSC207-UofT/course-project-marble#89]
Suggest to be fixed with moving BudgetHistory from Owner to Budget.

If a budget is inactive, use a 3 float digit to represent that it should not be counted when viewing history.

**Comment by a-gohar** [comment]
Bernard I believe we are fixing this by setting the values for an inactive budget to be null correct?

**Comment by by20c** [comment]
yep, null would stand for inactive budget at that time frame
